---

- name: Check existence of slovo-backend service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/slovo-backend.service"
  register: slovo_backend_service_stat

- when: slovo_backend_service_stat.stat.exists | bool
  block:
    - name: Ensure slovo-backend is stopped
      ansible.builtin.service:
        name: slovo-backend
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure slovo-backend.service doesn't exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/slovo-backend.service"
        state: absent

- name: Ensure slovo-backend container doesn't exist
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} rm -f slovo-backend"
  register: slovo_backend_container_removal_result
  changed_when: slovo_backend_container_removal_result.rc == 0
  failed_when: >-
    slovo_backend_container_removal_result.rc != 0
    and 'No such container' not in slovo_backend_container_removal_result.stderr
    and 'no such container' not in slovo_backend_container_removal_result.stderr

- name: Ensure slovo-backend paths don't exist
  ansible.builtin.file:
    path: "{{ slovo_backend_base_path }}"
    state: absent
  when: "slovo_backend_uninstall_remove_data | default(false) | bool"
