---

- name: Ensure slovo-adminer base path exists
  ansible.builtin.file:
    path: "{{ slovo_adminer_base_path }}"
    state: directory
    mode: '0750'
    owner: "{{ slovo_user_name }}"
    group: "{{ slovo_group_name }}"

- name: Ensure slovo-adminer labels file installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ slovo_adminer_base_path }}/labels"
    mode: '0640'
    owner: "{{ slovo_user_name }}"
    group: "{{ slovo_group_name }}"
  register: slovo_adminer_labels_file_changed

- name: Ensure slovo-adminer container image is pulled
  community.docker.docker_image_pull:
    name: "{{ slovo_adminer_container_image }}"
    pull: always
  register: slovo_adminer_container_image_pull_changed
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: slovo_adminer_container_image_pull_changed is not failed

- name: Ensure slovo-adminer container network is created
  when: slovo_adminer_container_network != 'host'
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ slovo_adminer_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure slovo-adminer.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/slovo-adminer.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/slovo-adminer.service"
    mode: '0644'
  register: slovo_adminer_systemd_unit_changed

- name: Determine whether slovo-adminer needs a restart
  ansible.builtin.set_fact:
    slovo_adminer_restart_necessary: >-
      {{
        slovo_adminer_labels_file_changed.changed | default(false)
        or slovo_adminer_container_image_pull_changed.changed | default(false)
        or slovo_adminer_systemd_unit_changed.changed | default(false)
      }}
