---

- name: Validate and install slovo-adminer
  tags:
    - setup-all
    - setup-slovo-adminer
    - install-all
    - install-slovo-adminer
  block:
    - name: Validate slovo-adminer configuration
      when: slovo_adminer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install slovo-adminer
      when: slovo_adminer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall slovo-adminer if disabled
  tags:
    - setup-all
    - setup-slovo-adminer
  block:
    - name: Uninstall slovo-adminer
      when: not slovo_adminer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
