---

- name: Validate and install slovo-minio
  tags:
    - setup-all
    - setup-slovo-minio
    - install-all
    - install-slovo-minio
  block:
    - name: Validate slovo-minio configuration
      when: slovo_minio_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install slovo-minio
      when: slovo_minio_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall slovo-minio if disabled
  tags:
    - setup-all
    - setup-slovo-minio
  block:
    - name: Uninstall slovo-minio
      when: not slovo_minio_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
