---

- tags:
    - setup-all
    - setup-slovo-docs
    - install-all
    - install-slovo-docs
  block:
    - when: slovo_docs_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: slovo_docs_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-slovo-docs
  block:
    - when: not slovo_docs_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
