---

- tags:
    - setup-all
    - setup-slovo-backup-nas
    - install-all
    - install-slovo-backup-nas
  block:
    - when: slovo_backup_nas_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: slovo_backup_nas_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-slovo-backup-nas
  block:
    - when: not slovo_backup_nas_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
