---

- name: Validate and install slovo-backup-nas
  tags:
    - setup-all
    - setup-slovo-backup-nas
    - install-all
    - install-slovo-backup-nas
  block:
    - name: Validate slovo-backup-nas configuration
      when: slovo_backup_nas_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install slovo-backup-nas
      when: slovo_backup_nas_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall slovo-backup-nas if disabled
  tags:
    - setup-all
    - setup-slovo-backup-nas
  block:
    - name: Uninstall slovo-backup-nas
      when: not slovo_backup_nas_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
