---

- name: Validate and install slovo-pgbouncer
  tags:
    - setup-all
    - setup-slovo-pgbouncer
    - install-all
    - install-slovo-pgbouncer
  block:
    - name: Validate slovo-pgbouncer configuration
      when: slovo_pgbouncer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install slovo-pgbouncer
      when: slovo_pgbouncer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Uninstall slovo-pgbouncer if disabled
  tags:
    - setup-all
    - setup-slovo-pgbouncer
  block:
    - name: Uninstall slovo-pgbouncer
      when: not slovo_pgbouncer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
