---

- tags:
    - setup-all
    - setup-slovo-pgbouncer
    - install-all
    - install-slovo-pgbouncer
  block:
    - when: slovo_pgbouncer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - when: slovo_pgbouncer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-slovo-pgbouncer
  block:
    - when: not slovo_pgbouncer_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
